In [0]:
import pandas as pd
import numpy as np

In [0]:
%run "/Workspace/Users/elizabethnguyen@ufl.edu/needs_requirements_notebook"

/home/spark-9421417e-8a2b-4429-a3be-e9/.ipykernel/2611/command-6230745727157871-1594228415:1: DtypeWarning: Columns (1,2,5,6,10,11,12,13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  needs = pd.read_csv('/Workspace/Users/elizabethnguyen@ufl.edu/hpc_hno_2025.csv')

       Country ISO3 Admin 1 PCode Admin 1 Name  ... Reached Info Cluster Full
47              AFG           NaN          NaN  ...     NaN  NaN  All Sectors
514             AFG          AF01        Kabul  ...     NaN  NaN  All Sectors
961             AFG           NaN          NaN  ...     NaN  NaN  All Sectors
1388            AFG           NaN          NaN  ...     NaN  NaN  All Sectors
1633            AFG           NaN          NaN  ...     NaN  NaN  All Sectors
...             ...           ...          ...  ...     ...  ...          ...
317954          YEM           NaN          NaN  ...     NaN  NaN  All Sectors
318018          YEM           NaN          NaN  ...     NaN  NaN  All Sectors
318082          YEM           NaN          NaN  ...     NaN  NaN  All Sectors
318156          YEM           NaN          NaN  ...     NaN  NaN  All Sectors
318215          YEM           NaN          NaN  ...     NaN  NaN  All Sectors

[3701 rows x 17 columns]

In [0]:
%run "/Workspace/Users/elizabethnguyen@ufl.edu/Adding_Country_Names"

     Unnamed: 0.2  Unnamed: 0.1  ...      funding percentFunded
0               0             0  ...    7101118.0          21.0
1               1             1  ...   80113551.0          86.0
2               2             2  ...   28287010.0          16.0
3               3             3  ...  202583088.0          19.0
4               4             4  ...  127002611.0          45.0
..            ...           ...  ...          ...           ...
429           429           429  ...    1545466.0          23.0
430           430           430  ...     477106.0         173.0
431           431           431  ...    1224531.0          12.0
432           432           432  ...      37778.0           4.0
433           433           433  ...     287425.0           2.0

[434 rows x 16 columns]

In [0]:
allocation_df = pd.read_csv("/Workspace/Users/elizabethnguyen@ufl.edu/cbpf_allocation_by_org_type.csv")

     Unnamed: 0.2  Unnamed: 0.1  ...      funding percentFunded
0               0             0  ...    7101118.0          21.0
1               1             1  ...   80113551.0          86.0
2               2             2  ...   28287010.0          16.0
3               3             3  ...  202583088.0          19.0
4               4             4  ...  127002611.0          45.0
..            ...           ...  ...          ...           ...
429           429           429  ...    1545466.0          23.0
430           430           430  ...     477106.0         173.0
431           431           431  ...    1224531.0          12.0
432           432           432  ...      37778.0           4.0
433           433           433  ...     287425.0           2.0

[434 rows x 16 columns]

     Unnamed: 0.2  Unnamed: 0.1  ...      funding  percentFunded
0               0             0  ...    7101118.0           21.0
1               1             1  ...   80113551.0           86.0
2               2             2  ...   28287010.0           16.0
3               3             3  ...  202583088.0           19.0
4               4             4  ...  127002611.0           45.0
..            ...           ...  ...          ...            ...
429           429           429  ...    1545466.0           23.0
430           430           430  ...     477106.0          173.0
431           431           431  ...    1224531.0           12.0
432           432           432  ...      37778.0            4.0
433           433           433  ...     287425.0            2.0

[434 rows x 16 columns]

Done 🎉

In [0]:
#Turn the columns into floats to prepare for operations
total_needs_for_all_cluster["In Need"] = total_needs_for_all_cluster["In Need"].astype(float)
allocation_df["Total Allocation"] = allocation_df["Total Allocation"].astype(float)

#Group the two dataframes by country
national_needs = total_needs_for_all_cluster.groupby("Country ISO3", as_index=False)["In Need"].sum()
national_allocations = allocation_df.groupby("Country Code", as_index=False)["Total Allocation"].sum()

#Merge the two dataframes by country
final_total_df = national_needs.merge(
    national_allocations,
    left_on="Country ISO3",
    right_on="Country Code",
    how="inner"
)

#Divide Total Allocation by In Need
final_total_df["Total"] = final_total_df["Total Allocation"] / final_total_df["In Need"]

final_total_df

/home/spark-9421417e-8a2b-4429-a3be-e9/.ipykernel/2611/command-6230745727158110-2313446639:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total_needs_for_all_cluster["In Need"] = total_needs_for_all_cluster["In Need"].astype(float)

   Country ISO3     In Need Country Code  Total Allocation     Total
0           AFG  68663182.0          AFG      7.343874e+07  1.069551
1           BFA  11830272.0          BFA      8.997558e+06  0.760554
2           COL  18106707.0          COL      0.000000e+00  0.000000
3           HTI  11972908.0          HTI      2.162359e+06  0.180604
4           MLI  12863066.0          MLI      8.012337e+06  0.622895
5           MMR  59707960.0          MMR      3.584838e+07  0.600395
6           MOZ   2610058.0          MOZ      2.287877e+06  0.876562
7           NER   5160657.0          NER      4.998012e+06  0.968484
8           NGA  15694096.0          NGA      1.949803e+07  1.242380
9           SDN  60881539.0          SDN      1.351765e+08  2.220319
10          SOM  11959482.0          SOM      5.724352e+07  4.786454
11          SSD  18580174.0          SSD      4.442582e+07  2.391033
12          TCD  21147677.0          TCD      1.061629e+07  0.502007
13          UKR  38126602.0          UKR      2.012069e+08  5.277337
14          VEN  15887440.0          VEN      8.965516e+06  0.564315
15          YEM  39080432.0          YEM      2.262208e+07  0.578860